_BASE_: ./base.yaml
task: ct_recon
exp_name: FBP_temp
lightning_module:
  name: CTLightningModule
model:
  name: CTO
  num_projections: 720
  sampler:
    name: MultiresSparseCTSampler
    accn_rate: [2, 5, 12, 20, 30]
  val_sampler:
    name: SparseCTSamplerKeepDim
    accn_rate: 30
  sino_reconstructor:
    name: IdentityReconstructor
  image_reconstructor:
    name: IdentityReconstructor
train_loss:
  name: MSELoss
val_test_loss:
  name: MSELoss