exp_name: equispaced_sparse_ct
trainer:
  max_epochs: 50
  lr: 0.001
  num_devices: 4
logger:
  project: "cto_cvpr"
  entity: null   # set the WANDB_ENTITY env var, or put your wandb username/team here; null uses your logged-in default
  save_dir: ./wandb